- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/Main.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
Instead of manipulating raw `ClassDef`s, we now first invoke the standard linker front-end to get a set of `LinkedClass`es. This way, we benefit from the existing reachability analysis and method synthesis (such as default method bridges).
One drawback is that abstract methods are removed from `LinkedClass`es, including in interfaces. We recover the ones we need with an additional pre-processing pass.
> Base the compilation on the result of the linker front-end.

- README.md
- run.mjs
- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Types.scala
This way, for the normal development flow, we do not even need the reference interpreter, and hence no Docker. We only need `deno` to be installed.
This commit includes fixing the opcodes of a number of nodes.
> Directly write the binary .wasm format to `target/output.wasm`.

- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
We introduce the global type `$string` as a typed struct containing a reference to an array of `i16`. We add support for loading string constants, and for converting primitive booleans to strings.
This is the minimum amount of support required to remove `java.lang.Boolean$` from the excluded list. Its `toString(b: bool)` method performs `"" String_+ b`.
This encoding of strings is hopefully temporary. Ideally we will want to use a Wasm `stringref` instead.
> Elementary infrastructure for strings.

- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/ir2wasm/LibraryPatches.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/utils/TestIRBuilder.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
After this PR, we only have the hijacked classes themselves and `java.lang.Class` in the exclude list.
> Implement enough things to enable the hijacked class companions.

- README.md
- build.sbt
- cli/src/main/scala/Main.scala
- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/Add.scala
- test-suite/src/main/scala/testsuite/core/Simple.scala
- tests/src/test/scala/tests/CoreTests.scala
- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/test/scala/MySuite.scala
Requires NodeJS >= 22 (for enough support of WasmGC).
With nvm, you can install the nightly version of Node with the following command. (but Node 22 should become a "current" version in April or May 2024).
```sh
$ NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly nvm install v22
```
- `tests/test` will
- Run `testSuite/run` to compile the Scala code under `test-suite` to WebAssembly
- Run the WebAssembly binary using NodeJS
- Each Scala program in `test-suite` should have a function that has no arguments and return a Boolean value. The test passes if the function returns `true`.
- When you add a test,
- Add a file under `test-suite`
- Add a test case to `cli/src/main/scala/TestSuites.scala` (`methodName` should be a exported function name).
> Setup a testing infrastructure

- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/AsInstanceOfTest.scala
- test-suite/src/main/scala/testsuite/core/HijackedClassesMonoTest.scala
- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/ir2wasm/LibraryPatches.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
This removes the last remaining exclude filters we had, including on the list of methods of `j.l.Object`.
> Support transformation of hijacked classes.

- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
~~Draft because based on #10, which should be merged before this one.~~
> Flat codegen with infrastructure for adaptions.

- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/InterfaceCall.scala
- test-suite/src/main/scala/testsuite/core/VirtualDispatch.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
We had sevelral problems with the vtable implementations
- We'd been generating a global vtable even for an abstract class, but it's not needed because we can't instantiate abstract class
- For calculating the vtable (both it's type and global instance), we filtered out the abstract methods. Therefore, we couldn't resolve a abstract method call from vtable.
For example,
```scala
class A extends B:
def a = 1
class B extends C:
def b: Int = 1
override def c: Int = 1
abstract class C:
def c: Int
```
The vtable type for C will be an empty table, because there's no concrete methods. Therefore, when we have `x: C`, `x.c` wond't resolve the implementation of `C` because vtable type doesn't have a slot for `c`.
The root cause is that we generated both of the following from one (in-memory) vtable …
> fix: Add tests for virtual dispatch + fix bug for abstract class

- build.sbt
- cli/src/main/scala/TestSuites.scala
- loader.mjs
- sample/src/main/scala/Sample.scala
- test-suite/src/main/scala/testsuite/core/JSInteropTest.scala
- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
This is all of the JS interop semantics at "use site". Not included are: exports, non-native JS classes and closure creation.
> Implement use-site JS interop.

- README.md
I have no idea what I'm doing, but, I found this to be necessary before I could `sample/run`
> Supply missing step in readme

- cli/src/main/scala/TestSuites.scala
- loader.mjs
- test-suite/src/main/scala/testsuite/Assert.scala
- test-suite/src/main/scala/testsuite/core/ClassOfTest.scala
- test-suite/src/main/scala/testsuite/core/GetClassTest.scala
- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/SpecialNames.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
Including elementary support of methods of `java.lang.Class`.
We implement this in a way that is similar to the JavaScript back-end: we have an internal `typeData` structure, which contains the raw metadata that will be needed by a `java.lang.Class` instance. It also contains a lazily evaluated pointer to the unique `java.lang.Class` and the `typeData` of an array of that type. If we need the `typeData` of a multi-dimensional array, we follow the chain of `arrayOf` pointers.
The name is initially stored as an `(array u16)` so that it can be initialized as a constant expression in globals. The `string` value is lazily initialized from that raw data the first time it is requested.
This machinery requires quite a bit of run-time helper functions. These are hard-coded in …
> Implement support for classOf and getClass.

- build.sbt
- project/plugins.sbt
- wasm/src/main/scala/ir2wasm/LibraryPatches.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/utils/TestIRBuilder.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
> Upgrade to Scala.js 1.16.0.

- test-suite/src/main/scala/testsuite/core/HijackedClassesDispatchTest.scala
- wasm/src/main/scala/ir2wasm/LibraryPatches.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
> Remove library patches; keep only our box classes.

- cli/src/main/scala/TestSuites.scala
- run.mjs
- sample/src/main/scala/Sample.scala
- test-suite/src/main/scala/testsuite/core/StaticMethodTest.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
> Add support for static methods.

- cli/src/main/scala/TestSuites.scala
- run.mjs
- sample/src/main/scala/Sample.scala
- test-suite/src/main/scala/testsuite/core/FieldsTest.scala
- test-suite/src/main/scala/testsuite/core/StaticMethodTest.scala
- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
In `LinkedClass`es, the `fields` only list fields declared directly in the given class. When allocating Wasm structs and computing indices, we must take inherited fields into account as well.
Based on #21.
> Take inherited fields into account.

- cli/src/main/scala/TestSuites.scala
- sample/src/main/scala/Sample.scala
- test-suite/src/main/scala/testsuite/core/ArrayTest.scala
- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Defaults.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
~Better to work based on https://github.com/tanishiking/scala-wasm/pull/15 for `js.Iterable`...~
Implement fundamental monomorphic array
- Generic array doesn't compile yet e.g. `Array.ofDim` because of https://github.com/scala-js/scala-js/blob/8dd02c784818d6d3d4a18ebf53cc0797212ef12e/javalib/src/main/scala/java/lang/Integer.scala#L56
- We would need to box Array so that it is a subtype of `java.lang.Object`(?) can we box it in `scala.Array` like `char` and `long`?
> Implement monomorphic Array

- cli/src/main/scala/TestSuites.scala
- loader.mjs
- test-suite/src/main/scala/testsuite/core/ClosureTest.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
> Implement support for Closures.

- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/ThrowablesTest.scala
- wasm/src/main/scala/ir2wasm/LibraryPatches.scala
So that we can successfully instantiate a `jl.Throwable` (though not actually throw it yet).
> Introduce a patched IR file for `java.lang.StackTrace$`.

- .github/workflows/ci.yml
- .scalafmt.conf
- project/plugins.sbt
- wasm/src/main/scala/Main.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/LibraryPatches.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/utils/MemClassDefIRFile.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
I personally don't care the style, but adding scalafmt to CI so we can reduce the unimportant diffs in PRs.
> CI: Check format using scalafmt

- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/IsInstanceOfTest.scala
- wasm/src/main/scala/Compiler.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
https://github.com/tanishiking/scala-wasm/issues/27
Current implementation is temporal and we should switch to the efficient type inclusion test implementation in future.
This impl test if the given expression is instance of the given interface by walking through the itables of the Object, which takes O(N) (where N = number of interfaces the expr implements)
Also, this procedure can't be extracted as a helper function in Wasm because the immediate argument of `ref.test` is specific to the `testClassName`, which result in a number of instructions everywhere at `isInstanceOf[interface]`.
see: https://github.com/tanishiking/scala-wasm/issues/27#issuecomment-2008252049
> Fix #27: Implement isInstanceOf[interface]

- cli/src/main/scala/TestSuites.scala
- loader.mjs
- test-suite/src/main/scala/testsuite/Assert.scala
- test-suite/src/main/scala/testsuite/core/WrapUnwrapThrowableTest.scala
- testrun.html
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/LibraryPatches.scala
- wasm/src/main/scala/ir2wasm/SpecialNames.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Defaults.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
Unfortunately, we cannot write unit tests for `TryCatch` and `TryFinally` yet. The latest Node.js nightly build is still using an old version of v8 that does not support the latest spec for Wasm exception handling. However, it possible to run the `sample` from a web browser when it contains `try..catch` and `try..finally`.
> Fix #32: Implement exception handling.

- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/MatchTest.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
The following Scala code will be compiled to
```scala
def fib(x: Int): Int = x match {
case 0     => 0
case 1 | 2 => 1
case _     => fib(x - 1) + fib(x - 2)
}
```
```wasm
block $done (result i32)
block $default
block $case1
block $case2
local.get $selector
i32.const 0
i32.eq
br_if $case1
local.get $selector
i32.const 1
i32.eq
br_if $case2
local.get $selector
i32.const 2
i32.eq
br_if $case2
br $default
end
i32.const 1
br $done
end
i32.const 0
br $done
end
;; default
end
```
I cound't find a practical way for using `br_table`. It seems that regardless, we still need to translate the selector into a range from 0 to X for `br_table` input.
In that case, it appears equivalent to convert the match patterns into a sequence of equality checks followed by `br_if` instruction. …
> Fix #35: Support Match

- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/NonNativeJSClassTest.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/LoaderContent.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
The handling of the IR Trees themselves are straightforward. The real work happens in `WasmBuilder`, and in particular in `genCreateJSClassFunction`. The main difficulty is that we need to decompose the JS constructor into three pieces, because the call to the super constructor must syntactically appear as such in the JavaScript source of the constructor. There is a big comment in the code that explains the decomposition.
> Fix #44: Support non-native JS classes.

- README.md
- build.sbt
- cli/src/main/scala/TestSuites.scala
- test-suite/src/main/scala/testsuite/core/ThrowAndTryTest.scala
Since Node.js 22 nightly from 2024/04/01, support for the new exceptions with `exnref` and `try_table` is available under a flag.
> Add tests for try..catch and try.finally.

- .scalafmt.conf
- build.sbt
- cli/src/main/scala/TestSuites.scala
- package-lock.json
- test-suite/src/main/scala/testsuite/core/HijackedClassesMonoTest.scala
- test-suite/src/main/scala/testsuite/core/StringEncodingTest.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
close https://github.com/tanishiking/scala-wasm/issues/18
- Add a passive data segment that stores the concatenated string (encoded in UTF-16LE)
-  `(data $string___data "\6e\00\61\00..."))`
- `getConstantStringInstr` call a `stringLiteral` helper function
- `stringLiteral` helper function does
- Check if the string literal is found in a global cache (`array of anyref`)
- if not found, gen i16 array using `array.new_data` and construct JS string using `createStringFromData` helper function, and cache it.
> Add const string to data section

- .sbtopts
- build.sbt
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
This allows to enable most of the `javalib.util.*` tests. The remaining failures are at run-time.
~~Based on #62.~~
> Implement dispatch of jl.Comparable.compareTo.

- .github/workflows/ci.yml
- README.md
- build.sbt
- wasm/src/main/scala/WebAssemblyLinkerBackend.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
* Do not emit `.wat` files unless `withPrettyPrint(true)`
* Do not emit the `"name"` section in the `.wasm` files under `fullLinkJS`
> Honor some of the linker config options to emit less stuff

- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Defaults.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
Overall, these changes bring our model closer to the "Structure" view of the WebAssembly specification, as opposed to the "Binary format" view of the spec. They also remove several levels of nesting of data structures, which makes the code less unwieldy.
> Refactoring: Simplify our model of WebAssembly.

- build.sbt
- test-suite/src/main/scala/testsuite/core/ReflectiveCallTest.scala
- tests/src/test/scala/tests/TestSuites.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
https://github.com/tanishiking/scala-wasm/issues/71
Added a `reflectiveProxies` field to `typeData`, this field contains an
array of struct with `methodId` of `i32`, and a reference to a
reflective proxy function.
When the compiler found an Apply to the reflective proxy, we lookup the
method to call from the `reflectiveProxies` field in the receiver's
`typeData` field, instead of normal table dispatching.
---
TODO (maybe in another PR)
- https://github.com/tanishiking/scala-wasm/pull/89#discussion_r1559340347
- reflective call on `java.lang.Object#clone`, it generates a following function, and it fails because a function `$f#java.lang.Void#clone_Ljava.lang.Object` doesn't exist.
```wasm
(func $f#java.lang.Void#clone_R (type $f.21)
(param $___<this> (ref any)) (result anyref)
local.get …
```
> Basic support of reflective calls

- build.sbt
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
This commit fixes the result of `x.isInstanceOf[C]` where `x` is a primitive and `C` is an ancestor of the hijacked class for `x`.
For `jl.Number`, which is the only non-`Object` class that is an ancestor of a hijacked class, we add a special case in the codegen.
For interfaces, we add generic code in their `genInstanceTest` function, based on their `specialInstanceTypes`.
This means we have a second place where we need to compute `specialInstanceTypes`. We move it to the preprocessor, and also use it to generically compute `isAncestorOfHijackedClass`. This removes the hard-code set that we had before.
Fix #74.
Fix #84.
Fix #92.
> Fix static type tests for ancestors of hijacked classes.

- build.sbt
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/LoaderContent.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
First switch to using the legacy `try` instruction to implement `TryCatch`, because `try_table` will only support catching `JSTag` from V8 12.5. Luckily we don't have to do that for `TryFinally`!
> Fix #75: Use WebAssembly.JSTag as our exception tag.

- build.sbt
- test-suite/src/main/scala/testsuite/core/TryFinallyReturnTest.scala
- tests/src/test/scala/tests/TestSuites.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
See the big "HERE BE DRAGONS" comment for details.
> Fix #101: Interaction between `TryFinally` and `Labeled`/`Return`.

- wasm/src/main/scala/wasm4s/WasmContext.scala
As commented in https://github.com/tanishiking/scala-wasm/pull/63#discussion_r1553207369 😄
> Refactor: use `toCharArray` to encode string to WTF-16

- wasm/src/main/scala/WebAssemblyLinkerBackend.scala
- wasm/src/main/scala/converters/WasmBinaryWriter.scala
- wasm/src/main/scala/converters/WasmTextWriter.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/org/scalajs/linker/backend/webassembly/SourceMapWriterAccess.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Wasm.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
- wasm/src/main/scala/wasm4s/WasmFunctionContext.scala
It turns out that source maps are supported for WebAssembly. Positions in the generated code are interpreted as
* a single line, and
* columns correspond to offsets in the `.wasm` file.
We reuse the Scala.js facility to create source maps per se. We feed it the right data from the binary writer.
To be consistent with how the Scala.js linker works when emitting JavaScript, we define a subclass of `WasmBinaryWriter` that handles source maps in addition of the regular output.
In our model, we store positions as fake `WasmInstr` every time the position (potentially) changes. This is in contrast with the JavaScript backend, which stores a `pos` in every `js.Tree`. There are typically several Wasm instructions that encode any particular `ir.Trees.Tree` (and therefore correspond to one …
> Generate source maps.

- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
Notably, when the rhs is a constant, we can emit straightforward code without any branches. This is worth it because the divisor of integer divisions and remainders is often constant in practice.
To handle the overflow case of `MinValue / -1`, we also remove one branch by turning `lhs / -1` into `0 - lhs`. The previous codegen used `if (lhs == MinValue) MinValue else lhs / -1` in the same situation.
> Generate simpler code for Int and Long division and remainder.

- wasm/src/main/scala/WebAssemblyLinkerBackend.scala
- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
When the statically resolved method of an `Apply` node exists and is "effectively final" (i.e., it is never overridden), we can use the compilation scheme of `ApplyStatically` instead.
This also allows to remove methods from the vtables if they are always called in such a situation.
The analysis is not optimal: consider 3 classes A, B, C. B and C both extend A, but only B overrides method m. Then a call on a `(c: C).m` will "resolve" to `A.m` which is not effectively final, so it won't be optimized. A better analysis would be costly in our setup, but will be free to obtain from the Scala.js Optimizer when we can enable it, so we don't push the design too much for now.
Nevertheless, it is worth doing now in its limited form. It reduces the size of the fastLink output by 18% and the …
> Statically resolve Apply calls when possible.

- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/TypeTransformer.scala
- wasm/src/main/scala/ir2wasm/WasmBuilder.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/Instructions.scala
- wasm/src/main/scala/wasm4s/Names.scala
- wasm/src/main/scala/wasm4s/Types.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
~~Based on #116. Only the last 3 commits belong to this PR.~~
> Better receiver types for static dispatch.

- wasm/src/main/scala/ir2wasm/HelperFunctions.scala
- wasm/src/main/scala/ir2wasm/Preprocessor.scala
- wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala
- wasm/src/main/scala/wasm4s/WasmContext.scala
This commit implements the "packed encoding" algorithm for compressing interface tables (itables). The algorithm is based on the paper "Efficient Type Inclusion Tests". https://www.researchgate.net/publication/2438441_Efficient_Type_Inclusion_Tests It compresses the itable by reusing itable indices for unrelated types, reducing the size of the itable array. For scalajs-test-suite, the itable size is reduced from 413 to 47.
This change didn't reduce the size of wasm binary that much (14957kb to 14943kb), but it should be space efficient.
We chose packed encoding because the compression rate is good enough among the presented methods in the paper. While hierarchical encoding is slightly better compression rate, packed encoding is better in both compile-time and runtime performance in CPU …
> Compress interface tables with packed encoding

- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/ClassEmitter.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/CoreWasmLib.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/Emitter.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/LoaderContent.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/VarGen.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/WasmExpressionBuilder.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/WasmFunctionContext.scala
- wasm/src/main/scala/org/scalajs/linker/backend/webassembly/FunctionBuilder.scala
This way, we use `WasmFunctionContext`+`WasmExpressionContext` only when we need to translate user-defined IR trees. In that case, the `WasmFunctionContext` is responsible for local name management: encoding from IR local names and generation of synthetic local names.
Otherwise, when we generate Wasm code independent of IR trees, we directly use `FunctionBuilder`. Local name management is left to the user code.
> Directly use FunctionBuilder when we do not need WasmExpressionBuilder.

- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/ClassEmitter.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/CoreWasmLib.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/FunctionEmitter.scala
- wasm/src/main/scala/org/scalajs/linker/backend/wasmemitter/WasmContext.scala
- wasm/src/main/scala/org/scalajs/linker/backend/webassembly/FunctionBuilder.scala
- wasm/src/main/scala/org/scalajs/linker/backend/webassembly/ModuleBuilder.scala
- wasm/src/main/scala/org/scalajs/linker/backend/webassembly/Modules.scala
They were isomorphic anyway, and the Wasm spec only has a notion of function type, even where we previously used function signature.
> Merge `FunctionSignature` and `FunctionType`.
